# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: ''

# Title of the Site
title: GMBS Consulting
# Logo of the Site
logo: '/assets/images/logo.png'
# Description of the Site
description: Making <em>REAL</em> Sense of Your Data
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: '/assets/images/cropped-wordcloud.png'

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: calldrpc@gmbs-consulting.com
facebook_username: gblumenthalscharf
twitter_username: /
instagram_username: /
linkedin_username: gm-blumenthal-scharf
github_username:  GregMBS
youtube_channel_id: /
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: /

# Disqus
disqus-shortname: /

# Name of the Author
author-name: Greg Blumenthal
# URL for the Image of the Author
author-image: https://media.licdn.com/dms/image/D4E35AQEUMg3B0SuOPw/profile-framedphoto-shrink_400_400/0/1697030658434?e=1708120800&amp;v=beta&amp;t=5b2P5B0kdXwj7E8c6S_31LykQCBTjIwVeg0gposieCU
# 60 Words About the Author
author-about: I solve business problems with integrated data solutions.
# URL to the Author's Profile (i.e., GitHub, Twitter, Stackoverflow, etc)
author-url: https://github.com/GregMBS

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
      path: ''
    values:
      layout: post
      post-image: ""
      description: ""
      tags: []
  -
    scope:
      type: 'pages'
      path: ''
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
